{{- if and .Values.config.createConfigMap .Values.config.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "check-if-email-exists.configMapName" . }}
  labels:
    {{- include "check-if-email-exists.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

