{{- if and .Values.config.createSecret (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-if-email-exists.secretName" . }}
  labels:
    {{- include "check-if-email-exists.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.config.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

